gui:
  mouseEvents: false
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}" --features=catppuccin-mocha
  commitPrefix:
    pattern: "^\\w+\\/(\\w+-\\d+).*"
    replace: "[$1] "
