return {
  "nvim-treesitter/nvim-treesitter",
  version = false,
  build = ":TSUpdate",
  event = { "BufReadPost", "BufNewFile" },
  cmd = { "TSUpdateSync" },
  opts = {
    highlight = { enable = true },
    indent = { enable = true },
    ensure_installed = {
      "astro",
      "bash",
      "c",
      "css",
      "c_sharp",
      "dockerfile",
      "gitignore",
      "go",
      "gomod",
      "gosum",
      "html",
      "http",
      "javascript",
      "jq",
      "jsdoc",
      "json",
      "lua",
      "luadoc",
      "luap",
      "make",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "sql",
      "terraform",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
    },
    auto_install = true,
  },
  config = function(_, opts)
    local treesitter = require("nvim-treesitter.configs")

    treesitter.setup(opts)
  end,
}
